name: Create issue comment
description: Create issue comment
inputs:
  owner:
    description: 'Owner'
    required: true
    type: string
  repo:
    description: 'Repo'
    required: true
    type: string
  issue_number:
    description: 'Issue number'
    required: true
    type: int
  token:
    description: 'Token'
    required: true
    type: string
  body:
    description: 'Body'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Create comment
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/issues/${{ inputs.issue_number }}/comments \
          -d '{"body":"${{ inputs.body }}"}'
