name: Setup ssh key and known_hosts
description: Setup ssh key and known_hosts
inputs:
  ssh-key:
    description: 'SSH key'
    required: true
    type: string
  ssh-agent-socket:
    description: 'SSH agent socket'
    required: true
    type: string
  home-dir:
    description: 'Home directory'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup ssh key and known_hosts
      shell: bash
      run: |
        mkdir -p ${{ inputs.home-dir }}/.ssh
        ssh-keyscan github.com >> ${{ inputs.home-dir }}/.ssh/known_hosts
        echo "${{ inputs.ssh-key }}" > ${{ inputs.home-dir }}/.ssh/github_actions
        chmod 600 ${{ inputs.home-dir }}/.ssh/github_actions
        eval $(ssh-agent -a ${{ inputs.ssh-agent-socket }})
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
        ssh-add ${{ inputs.home-dir }}/.ssh/github_actions
