name: Setup ssh key and known_hosts
description: Setup ssh key and known_hosts
inputs:
  ssh-key:
    description: 'SSH key'
    required: true
    type: string
  home-directory:
    description: 'Home directory'
    default: /home/runner
    type: string
  known-hosts:
    description: 'Known hosts'
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Prepare directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.home-directory }}/.ssh
    - name: Add known hosts
      shell: python3 {0}
      run: |
        import os
        known_hosts = "${{ inputs.known-hosts }}"
        known_hosts = known_hosts.split(',')
        for host in known_hosts:
          if host != "":
            os.system(f"ssh-keyscan {host} >> ${{ inputs.home-directory }}/.ssh/known_hosts")
    - name: Setup ssh key and known_hosts
      shell: bash
      run: |
        eval $(ssh-agent)
        echo "${{ inputs.ssh-key }}" | ssh-add -
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
