name: Pull single file from a repository
description: Pull single file from a repository
inputs:
  ssh-key:
    description: 'SSH key'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup ssh key and known_hosts
      shell: bash
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "${{ inputs.ssh-key }}" > ~/.ssh/github_actions
        chmod 600 ~/.ssh/github_actions
        ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
        ssh-add ~/.ssh/github_actions
