name: Render Jinja2 template
description: Render Jinja2 template
inputs:
  template_file:
    description: 'Template file location <path-to-template.j2>'
    required: true
    type: string
  data_file:
    description: 'Data file location <path-to-data.yaml>'
    required: true
    type: string
  output_file:
    description: 'Output file location <path-to-output>'
    required: true
    type: string
outputs:
  output_file:
    description: 'Output file location <path-to-output>'
    value: ${{ steps.render-template.outputs.output_file }}
runs:
  using: "composite"
  steps:
    - name: Render template
      id: render-template
      shell: python3 {0}
      run: |
        import jinja2, yaml, pathlib, os
        output_file = pathlib.Path('${{ inputs.output_file }}').absolute()
        with open('${{ inputs.data_file }}', 'r') as f:
          data = yaml.safe_load(f)
        with open('${{ inputs.template_file }}', 'r') as f:
          template = jinja2.Template(f.read())
        with open(output_file, 'w') as f:
          f.write(template.render(data))
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          f.write(f'output_file={ output_file }\n')
